POST https://api-nodejs-fastify-postgres.onrender.com/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Primeiro video",
  "duration": 60
}


####


GET https://api-nodejs-fastify-postgres.onrender.com/videos


###
 

PUT  https://api-nodejs-fastify-postgres.onrender.com/videos/2868118c-d8ec-4b47-bf16-2386f9066505
Content-Type: application/json

{
  "title": "Video Atualizado",
  "description": "Att video",
  "duration": 90
}


###


DELETE https://api-nodejs-fastify-postgres.onrender.com/videos/4dfa24a9-a26e-4266-b361-df7f67eeae75